# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    weight: 90
    url: uploads/resume.pdf
  - name: Teaching Portfolio
    weight: 120
    url: https://fr.slideshare.net/QuentinMoreau12/edit_my_uploads



# # Link to a PDF of your resume/CV from the menu.
# # To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  
